namespace QrSharp;

public abstract class AbstractQrCode
{
    protected AbstractQrCode()
    {
    }

    protected AbstractQrCode(QrCodeData data)
    {
        QrCodeData = data;
    }

    protected QrCodeData QrCodeData { get; private set; } = null!;

    /// <summary>
    ///     Set a QrCodeData object that will be used to generate Qr code. Used in COM Objects connections
    /// </summary>
    /// <param name="data">Need a QrCodeData object generated by QrCodeGenerator.CreateQrCode()</param>
    public virtual void SetQrCodeData(QrCodeData data)
    {
        QrCodeData = data;
    }

    public void Dispose()
    {
        QrCodeData.Dispose();
    }
}